[package]
name = "wave_forms"
version = "0.1.0"
edition = "2021"
description = "no std wave forms"
license = "MIT"
repository = "https://github.com/Loag/sinusoidal" # optional but recommended
documentation = "https://docs.rs/wave_forms"      # optional
readme = "README.md"
