name: CI

on:
  release:
    types: [created]

jobs:
  publish-library:
    name: Publish Library
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build wave_forms library crate
        run: cd wave_forms && cargo publish --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO }}
        continue-on-error: true

  release-binaries:
    name: Release Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: sinusoidal
            asset_name: sinusoidal-linux-amd64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: sinusoidal
            asset_name: sinusoidal-macos-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: sinusoidal.exe
            asset_name: sinusoidal-windows-amd64.exe
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build cli binary
        run: cd cli && cargo build --release --target ${{ matrix.target }} --bin sinusoidal

      - name: Rename binary
        shell: bash
        run: |
          cp cli/target/${{ matrix.target }}/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.asset_name }}
